<a href="https://colab.research.google.com/github/Mohanee28/06July2024/blob/main/Linear_Algebra_Handson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear algebra Handson

In [3]:
import numpy as np
import pandas as pd

In [4]:
a = np.array ([[2,3], [3,4]])
b = np.array ([[1,2], [4,2]])

In [5]:
a

array([[2, 3],
       [3, 4]])

In [6]:
b

array([[1, 2],
       [4, 2]])

##Matrix Operation
##Addition, Subtraction, Multiplication

In [7]:
a+b

array([[3, 5],
       [7, 6]])

## Element wise addition aij + bij
## Nested for loop (more recomented for element wise addition)

In [11]:
result = np.array([[0,0],[0,0]])
for i in range(len(a)):
  for j in range(len(a[0])):
    result[i][j] = a[i][j]+b[i][j]
for r in result:
  print(r)

[3 5]
[7 6]


##vector based row addition ai + bi (add entier row)

In [14]:
result = np.array([[0,0],[0,0]])
for i in range(len(a)):
  result[i] = a[i]+b[i]
for r in result:
  print(r)

[3 5]
[7 6]


In [15]:
len(a)

2

In [16]:
len(a[0])

2

In [17]:
result = np.array([[0,0],[0,0]])
for i in range(len(a)):
  result[i] = a[i]+b[i]
  print(result[i])

[3 5]
[7 6]


In [19]:
##Subtracting
a = np.array ([[2,3,4],[3,4,5],[4,1,3]])
b = np.array ([[1,2,3],[2,3,4],[2,1,3]])
result = np.array([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(a)):
  for j in range(len(a[0])):
    result[i][j] = a[i][j]-b[i][j]
for r in result:
  print(r)

[1 1 1]
[1 1 1]
[2 0 0]


In [22]:
## Scalar Multiplication
c = np.array([[2,6,4],[7,4,3],[4,9,7]])
scalar = 2

In [25]:
c

array([[2, 6, 4],
       [7, 4, 3],
       [4, 9, 7]])

In [28]:
mul_result = np.array([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(a)):
  mul_result[i] = scalar*c[i]
for r in mul_result:
  print(r)

[ 4 12  8]
[14  8  6]
[ 8 18 14]


In [31]:
mul_result = np.array([[0,0,0],[0,0,0],[0,0,0]])
for i in range(len(a)):
  for j in range(len(a[0])):
    mul_result[i][j] = scalar*c[i][j]
for r in mul_result:
  print(r)

[ 4 12  8]
[14  8  6]
[ 8 18 14]


In [35]:
scalar1 = np.array([1,2,3])
mul_result = c*scalar1
for row in mul_result:
  print(row)

[ 2 12 12]
[7 8 9]
[ 4 18 21]


In [38]:
## for Dot product ----> number of column  = no of rows (3,3) * (3,1)
c= np.array([[5,2,9],[4,6,7],[1,3,8]])
d= np.array([[1],[2],[4]])
result = np.dot(c,d)
print(result)

[[45]
 [44]
 [39]]


In [39]:
## for Dot product ----> number of column  = no of rows (3,3) * (3,2)
c= np.array([[5,2,9],[4,6,7],[1,3,8]])
d= np.array([[1,2],[2,1],[1,2]])
result = np.dot(c,d)
print(result)

[[18 30]
 [23 28]
 [15 21]]


In [43]:
a = np.array([[3],[2],[8]])
b = np.array([[2],[9],[7]])

In [44]:
a.shape

(3, 1)

In [45]:
b.shape

(3, 1)

##The cross product is a mathematical operation defined only for two vectors in three-dimensional space (R^3). Since your input arrays, a and b, have only three elements each, we will treat them as 3D vectors.

##The cross product of two vectors, aXb, results in a new vector that is perpendicular (orthogonal) to both a and b.

In [48]:
cross = np.cross(np.transpose(a), np.transpose(b))
cross

array([[-58,  -5,  23]])

In [52]:
c = np.transpose(a)
c

array([[3, 2, 8]])

In [53]:
b

array([[2],
       [9],
       [7]])

In [51]:
np.transpose(b)

array([[2, 9, 7]])

In [57]:
c1 = np.dot(c,b)
c1

array([[80]])

In [62]:
c= np.array([[5,2,9],[4,6,7],[1,3,8]])
cross2 = np.cross(c[0],c[1])
cross2

array([-40,   1,  22])

In [63]:
c

array([[5, 2, 9],
       [4, 6, 7],
       [1, 3, 8]])

In [64]:
c= np.array([[5,2,9],[4,6,7],[1,3,8]])
d= np.array([[9,2,5],[6,7,4],[8,3,1]])
cross2 = np.cross(c,d)
cross2

array([[ -8,  56,  -8],
       [-25,  26,  -8],
       [-21,  63, -21]])

In [65]:
##Inverse matrix
f = np.array([[5,2,9],[4,6,7],[1,3,8]])
Inv = np.linalg.inv(f)
print(Inv)

[[ 0.1942446   0.07913669 -0.28776978]
 [-0.17985612  0.22302158  0.00719424]
 [ 0.04316547 -0.09352518  0.15827338]]


In [73]:
##Rank of a matrix
H = np.array([[1,2,2],[0,1,4],[2,4,4]])
Rank = np.linalg.matrix_rank(H)
print("Rank of the matrix H is:", str(Rank))

Rank of the matrix H is: 2


In [75]:
##Eigen values and Eigen vectors
m = np.array([[5,2,9],[4,6,7],[1,3,8]])
E_value, E_vector = np.linalg.eig(m)
print(E_value, E_vector)

[13.9926379 +0.j          2.50368105+1.91451729j  2.50368105-1.91451729j] [[ 0.58942558+0.j          0.68982543+0.j          0.68982543-0.j        ]
 [ 0.67869449+0.j         -0.10619009-0.63402908j -0.10619009+0.63402908j]
 [ 0.43812243+0.j         -0.16773823+0.28763788j -0.16773823-0.28763788j]]


In [76]:
m

array([[5, 2, 9],
       [4, 6, 7],
       [1, 3, 8]])

##SVD --> Singular value decomposition
kind of dimentionality reduction - reducess the dimention (lat, log)

In [77]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
U, S, VT = np.linalg.svd(A)

In [78]:
U

array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]])

In [79]:
S

array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16])

In [80]:
VT

array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]])